name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    environment: main
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.set_latest_tag.outputs.latest_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install musl cc
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools musl-dev musl
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache: false  # Disable built-in caching to use custom caching
      - name: Tag Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          release_branches: main
          tag_prefix: v
      - name: Cache Go Modules and Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}-
            ${{ runner.os }}-go-
      - name: Configure Git for Private Repos
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/opengovern.insteadOf https://github.com/opengovern
      - name: Build Github Plugin App
        working-directory: ./plugin/cloudql
        run: make build
      - name: Pack Github Plugin Build
        working-directory: ./plugin/cloudql
        run: |
          tar -cvf build.tar build
      - name: Upload Github Plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-github
          path: ./plugin/cloudql/build.tar
          retention-days: 1
      - name: Build Local Describer App
        working-directory: ./describer
        run: make build-describer
      - name: Pack Local Describer Build
        working-directory: .
        run: |
          tar -cvf local.tar local
      - name: Upload Local Artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-og-describer-github
          path: ./local.tar
          retention-days: 1
      - name: Build Integration Plugin
        working-directory: ./plugin/integration
        run: make build
      - name: Create output directory
        working-directory: .
        run: mkdir -p github-output
      - name: Copy steampipe plugin to output directory
        working-directory: .
        run: cp ./plugin/cloudql/build/steampipe-plugin-github.plugin ./github-output/cloudql-plugin
      - name: Copy integration plugin to output directory
        working-directory: .
        run: cp ./plugin/integration/build/integration-plugin ./github-output/
      - name: Copy manifest to output directory
        working-directory: .
        run: cp ./plugin/integration/manifest.yaml ./github-output/
      - name: Pack output
        working-directory: .
        run: |
          tar -czf github-output.tar github-output
      - name: Upload github outputs artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-outputs
          path: ./github-output.tar
          retention-days: 1

      - name: Set Latest Tag Output
        id: set_latest_tag
        run: |
          if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
            echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          fi
  deploy-github-plugin:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Github Plugin Artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-github
          path: .
      - name: Unpack Github Plugin Artifact
        run: |
          tar -xvf build.tar
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and Push Docker Image for Github Plugin
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/steampipe-plugin-github:0.0.1
            ghcr.io/${{ github.repository_owner }}/steampipe-plugin-github:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-github/docker/Dockerfile
          context: .
  deploy-local-describer:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Local Describer Artifact
        uses: actions/download-artifact@v3
        with:
          name: local-og-describer-github
          path: .
      - name: Unpack Local Describer Artifact
        run: |
          tar -xvf local.tar
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and Push Docker Image for Local Describer
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/og-describer-github:local-latest
            ghcr.io/${{ github.repository_owner }}/og-describer-github:local-${{ needs.build.outputs.latest_tag }}
          file: describer/DockerFile
          context: .
  release-integration-plugin:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Integration Plugin Artifact
        uses: actions/download-artifact@v3
        with:
          name: github-outputs
      - name: Unpack Integration Plugin Artifact
        run: |
          tar -xvf github-output.tar
      - name: Pack folder content into a zip file for release
        run: |
          cd github-output
          zip -r github-output.zip .
      - name: Release Integration Plugin
        uses: softprops/action-gh-release@v2
        with:
          files: ./github-output/github-output.zip
          tag_name: ${{ needs.build.outputs.latest_tag }}